// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGwTPUBEImqWGzs02Y-5VDRdW8mp50ygs',
    appId: '1:301510488418:web:cc15921c0ff02f29cfbc3b',
    messagingSenderId: '301510488418',
    projectId: 'arta-e0c53',
    authDomain: 'arta-e0c53.firebaseapp.com',
    storageBucket: 'arta-e0c53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYP5gd-iBb2Odv_gwnSXWjN2YNRSVqwGg',
    appId: '1:301510488418:android:5aee59f34a754aa8cfbc3b',
    messagingSenderId: '301510488418',
    projectId: 'arta-e0c53',
    storageBucket: 'arta-e0c53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGwVRDld5WTruK2ndC4XC2xztiieMLFeM',
    appId: '1:301510488418:ios:fb3690ec8b36904ccfbc3b',
    messagingSenderId: '301510488418',
    projectId: 'arta-e0c53',
    storageBucket: 'arta-e0c53.firebasestorage.app',
    iosBundleId: 'com.example.arta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGwVRDld5WTruK2ndC4XC2xztiieMLFeM',
    appId: '1:301510488418:ios:fb3690ec8b36904ccfbc3b',
    messagingSenderId: '301510488418',
    projectId: 'arta-e0c53',
    storageBucket: 'arta-e0c53.firebasestorage.app',
    iosBundleId: 'com.example.arta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGwTPUBEImqWGzs02Y-5VDRdW8mp50ygs',
    appId: '1:301510488418:web:1e3ecf680848e512cfbc3b',
    messagingSenderId: '301510488418',
    projectId: 'arta-e0c53',
    authDomain: 'arta-e0c53.firebaseapp.com',
    storageBucket: 'arta-e0c53.firebasestorage.app',
  );
}
